[package]
name = "ads131m"
version = "0.1.0"
authors = ["Kinnon McAlister <kinnonmcalister@gmail.com>"]
repository = "https://github.com/eloc3147/ads131m"
license = "MIT OR Apache-2.0"
description = "Rust driver for the Texas Instruments ADS131M series of simultaneously sampling 24-bit delta-sigma analog-to-digital converters."
readme = "README.md"
keywords = ["adc", "analog", "driver", "spi", "embedded-hal-driver"]
categories = ["embedded", "hardware-support", "no-std"]
homepage = "https://github.com/eloc3147/ads131m"
documentation = "https://crouton.net"  # TODO: Add docs.rs link
include = [
    "/**/*.rs",
    "/Cargo.toml",
    "/README.md",
    "/LICENSE-MIT",
    "/LICENSE-APACHE",
]
edition = "2021"

[dependencies]
nb = "1"
embedded-hal = "0.2.7"

[profile.release]
lto = true
